version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_app
    ports:
      - "5006:5006"
    environment:
      - ConnectionStrings__PostgreSqlConnection=Host=db;Database=DB_FIAP_ARQUITETO;Username=postgres;Password=Teste@123
      - ASPNETCORE_URLS=http://+:5006
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - db-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: DB_FIAP_ARQUITETO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Teste@123
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/FiapDB.sql:/docker-entrypoint-initdb.d/FiapDB.sql
    networks:
      - db-network

  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - "9090:9090"
    networks:
      - db-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'  

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - db-network
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    depends_on:
      - prometheus

networks:
  db-network:
    driver: bridge

volumes:
  grafana-storage:
